config/routes.rb
Rails.application.routes.draw do
  
  root to: "home#index"
  devise_for :users
  get 'users/account'
  get 'users/profile', to: 'users#profile'
  post 'users/profile', to: 'users#update'

  get 'rooms/posts', to: 'rooms#posts'
  resources :rooms do
    collection do
      get 'search'
    end
  end
  
  resources :reservations

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  mount_uploader :image, ImageUploader

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :address, presence: true
  validates :image, presence: true


  belongs_to :user
  has_many :reservations
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  validates :name, presence: true
  
  validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  
  mount_uploader :image, ImageUploader

  has_many :rooms

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # ユーザーページにアクセス前に実行
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_q

  private
  
  # サインアップ時にnameを許可する
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def set_q
    @q = Room.ransack(params[:q])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  require "date"

  def index
    @reservations = Reservation.all
  end

  def new
    @reservation = Reservation.new(reservation_params)
    if @reservation.start_date < Date.today
      flash[:alert] = "開始日は本日以降の日付を選択してください"
      @room = Room.find(params[:room_id])
      redirect_to @room

    elsif @reservation.end_date <= @reservation.start_date
      flash[:alert] = "終了日は開始日の翌日以降の日付を選択してください"
      @room = Room.find(params[:room_id])
      redirect_to @room

    else
      @room = Room.find_by(id: params[:room_id])
      start_date = @reservation.start_date
      end_date = @reservation.end_date
      # 使用日数
      @reservation_days = (end_date - start_date).to_i / 86400
      # 合計金額
      @reservation.total_price = @room.price * @reservation.num_person * @reservation_days
    end
  end
  
  def create
    @room = Room.find_by(id: params[:room_id])
    @reservation = Reservation.create(reservation_params)
    flash[:notice] = "予約が完了しました"
    redirect_to reservation_path(@reservation.id)
  end
  
  def show
    @reservation = Reservation.find(params[:id])
    @room = Room.find(@reservation.room_id)
  end

  private

    def reservation_params
      params.permit(:total_price, :start_date, :end_date, :room_id, :num_person)
    end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def search
    @results = @q.result
    @q = Room.ransack
  end

  def posts
    @rooms = Room.where(user_id: current_user.id)
  end

  def new
    @user = User.find(current_user.id)
    @room = Room.new
  end
  
  def create
    @room = Room.new(room_params)
    if @room.save
      flash[:notice] = "新規ルーム登録に成功しました"
      redirect_to :root
    else
      @user = User.find(current_user.id)
      flash.now[:alert] = "登録に失敗しました"
      render 'new'
    end
  end

  def show
    @user = User.find(current_user.id)
    @room = Room.find(params[:id])
    @reservation = Reservation.new(reservation_params)
  end

  private

    def room_params
      params.permit(:image, :name, :introduction, :price, :address, :user_id)
    end

    def reservation_params
      params.permit(:image, :name, :introduction, :total_price, :start_date, :end_date, :room_id, :num_person, :day_price)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # アクセス権限 => ログイン済みのユーザーのみ
  before_action :authenticate_user!

  def account
  end
  
  def profile
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(current_user.id)

    if @user.update(user_params)
      flash[:notice] = "プロフィールを更新しました"
      redirect_to users_profile_path
    else
      flash.now[:notice] = "更新に失敗しました"
      render :users_profile_path
    end
  end
  
  private

    def user_params
      params.permit(:image, :name, :profile)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="top">
  <div class="top-main">
    <div class="container">
      <div class="row col-lg-6">
        <div class="form-fream">
          <div class="form-area">
            <p class="form-area-title mb-4">Potepan Shareでまだ体験したことのない旅をしよう</p>

            <%= search_form_for @q, url: search_rooms_path do |f| %>
              <%= f.label :address_cont, 'エリア' %>
              <%= f.search_field :address_matches, id: "area", class: "form-control mb-4", placeholder: "東京" %>
              <br>
              <%= f.submit '探す', class: "form-control btn-primary mb-4" %>
            <% end %>
            
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="panel-area m-5">
      <h1 class="section-title">おすすめのエリア</h1>
      <div class="row">
        <div class="panel-item col-lg-3 col-6">
          <span>東京</span>
          <%= link_to image_tag("https://presite-potepancamp-rails-02.herokuapp.com/assets/img_tokyo.jpg", class: "panel-image"), search_rooms_path(q: {address_cont: "東京"}) %>
        </div>
        <div class="panel-item col-lg-3 col-6">
          <span>大阪</span>
          <%= link_to image_tag("https://presite-potepancamp-rails-02.herokuapp.com/assets/img_osaka.jpg",class: "panel-image"), search_rooms_path(q: {address_cont: "大阪"}) %>
        </div>
        <div class="panel-item col-lg-3 col-6">
          <span>京都</span>
          <%= link_to image_tag("https://presite-potepancamp-rails-02.herokuapp.com/assets/img_kyoto.jpg", class: "panel-image"), search_rooms_path(q: {address_cont: "京都府"}) %>
        </div>
        <div class="panel-item col-lg-3 col-6">
          <span>札幌</span>
          <%= link_to image_tag("https://presite-potepancamp-rails-02.herokuapp.com/assets/img_sapporo.jpg", class: "panel-image"), search_rooms_path(q: {address_cont: "札幌"}) %>
        </div>
      </div>
    </div>
  </div>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotelReservationApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="header-inner">

        <div class="header-left-nav">
          <a href="/"><img src="https://presite-potepancamp-rails-02.herokuapp.com/assets/logo.png" alt="サイトロゴ"></a>
          <div class="header-sharch d-lg-inline-block d-none">

            <%= search_form_for @q, url: search_rooms_path do |f| %>
            <%= f.search_field :address_cont, id: "search_area", class: "form-control", placeholder: "エリア" %>
            <% f.submit '探す', class: "form-control btn-primary mb-4" %>
            <% end %>
            <i class="fa-solid fa-location-dot fa-lg"></i>

          </div>
          <div class="header-sharch d-lg-inline-block d-none">
            
            <%= search_form_for @q, url: search_rooms_path do |f| %>
            <%= f.search_field :name_or_address_or_introduction_cont, id: "search_area", class: "form-control", placeholder: "キーワード" %>
            <% f.submit '探す', class: "form-control btn-primary mb-4" %>
            <% end %>
            <i class="fa-solid fa-magnifying-glass fa-lg"></i>

          </div>
        </div>

        <div class="header-right-nav">
          <div class="nav-item ">

            <% if user_signed_in? %>
            <div class="nav-item d-sm-inline-block"><%= current_user.name %></div>
            <div class="nav-item">
              <% if current_user.image.blank? %>
                <img src="https://presite-potepancamp-rails-02.herokuapp.com/assets/default_icon-9263fc59c414b7228d256fc178dcb22183561357950a68f5ad086ba7ee054974.jpg" alt='メニュー' class="mx-3 p-1 host-icon nav-trigger">
              <% else %>
                <%= image_tag current_user.image.url, alt: "メニュー", class: "mx-3 p-1 host-icon nav-trigger" %>
              <% end %>  

              <ul class="header-nav-menu">
                <li>
                  <%= link_to "ルーム登録", new_room_path %>
                </li>
                <li>
                  <%= link_to "予約済みルーム一覧", reservations_path %>
                </li>
                <li>
                  <%= link_to "登録済みルーム一覧", rooms_posts_path %>
                </li>
                <li>
                  <%= link_to "ユーザー設定", users_account_path %>
                </li>
                <li>
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                </li>
              </ul>
              <script>
                'use strict';
                {
                  document.querySelector('.nav-trigger').addEventListener('click', ()=> {
                    document.querySelector('.header-nav-menu').classList.toggle('on');
                  });
                }
              </script>
            </div>
            <% else %>
            <%= link_to "ログイン", new_user_session_path, class: "btn btn-primary my-2 mx-3" %>
            <%= link_to "登録する", new_user_registration_path, class: "btn btn-secondary" %>
            <% end %>

          </div>
        </div>

      </div>
    </header>

    <% if flash[:notice] %>
      <div class="notifications">
      <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="notifications">
      <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <%= yield %>

    <footer class="footer">
      <p>© 2020 POTEPAN.INC.</p>
    </footer>
  </body>
</html>

app/views/reservations/index.html.erb
<div class="conainer-fiuld reservations">
  <h4 class="pb-4">予約済みルーム一覧</h4>

  <table>
    <thead>
      <tr align="center">
        <th>ルーム画像</th>
        <th>ルーム名</th>
        <th>ルーム紹介</th>
        <th>合計料金</th>
        <th>開始日</th>
        <th>終了日</th>
        <th>予約確定日時</th>
      </tr>
    </thead>
    
    <% @reservations.each do |reservation| %>
    
    <tbody>
      <tr>
        <td>
          <%= link_to image_tag(Room.find(reservation.room_id).image.url, alt: "ルーム画像", class: "room-posts-image"), room_path(Room.find(reservation.room_id).id) %>
        </td>
        <td class="posts-name">
          <%= link_to Room.find(reservation.room_id).name, room_path(Room.find(reservation.room_id).id) %>
        </td>
        <td class="posts-content">
          <%= Room.find(reservation.room_id).introduction %>
        </td>
        <td class="price-icon">
          <%= reservation.total_price %>
        </td>
        <td>
          <%= reservation.start_date.strftime("%Y-%m-%d") %>
        </td>
        <td>
          <%= reservation.end_date.strftime("%Y-%m-%d") %>
        </td>
        <td>
          <%= reservation.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
        </td>
      </tr>
    </tbody>

    <% end %>

  </table>
</div>

app/views/reservations/new.html.erb
<div class="container reservations-new">
  <div class="row">
    <div class="col-6 offset-3">
      <div class="reservations-new-nav">
        <h4 class="reservations-new-check-content">予約内容確認</h4>
        <h5 class="price-icon">
          <%= "#{@room.price} / 日" %>
        </h5>
        <div class="reservations-new-date-select">

          <%= form_with url: reservations_path do |f| %>
            <%= f.label :reservation_end, "開始日" %>
            <%= f.text_field :start_date, value: @reservation.start_date.strftime("%Y-%m-%d"), readonly: true, class: "form-control mb-4" %>

            <%= f.label :reservation_end, "終了日" %>
            <%= f.text_field :end_date, value: @reservation.end_date.strftime("%Y-%m-%d"), readonly: true, class: "form-control mb-4" %>

            <h6 class="reservations-new-check-content">使用日数：<%= @reservation_days %>日</h6>
            <h6 class="reservations-new-check-content">人数：<%= @reservation.num_person %>人</h6>

            <%= f.label :total_price, "合計金額" %>
            <%= f.text_field :total_price, value: "¥ #{@reservation.total_price}", readonly: true, class: "form-control mb-4" %>

            <%= f.hidden_field :room_id, value: @room.id %>
            <% start_date = @reservation.start_date %>
            <% end_date = @reservation.end_date %>
            <% @reservation_days = (end_date - start_date).to_i / 86400 %>
            <%= f.hidden_field :num_person, value: @reservation.num_person %>
            <%= f.hidden_field :total_price, value: (@room.price * @reservation.num_person * @reservation_days) %>

            <p class="reservations-new-check-content">上記内容でよろしければ「予約を確定」を押してください</p>
            <%= f.submit"予約を確定", class: "btn btn-primary form-control my-3" %>
            <%= link_to "ルーム詳細に戻る", room_path(@room.id), class: "btn btn-secondary form-control" %>
          <% end %>
          
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reservations/show.html.erb
<div class="container-fiuld user">
  <div class="row">
    <div class="col-md-12 user-view">
      <div class="user-view-box">

        <div class="update-content">
          <div class="row">
            <label for="room" class="col-md-3">予約した部屋</label>
            <div class="col-md-9">
              <%= link_to @room.name, room_path(@room.id) %>
            </div>
          </div>
        </div>

        <div class="update-content">
          <div class="row">
            <label for="start_date" class="col-md-3">開始日</label>
            <div class="col-md-9">
              <%= @reservation.start_date.strftime("%Y年 %m月 %d日") %>
            </div>
          </div>
        </div>

        <div class="update-content">
          <div class="row">
            <label for="end_date" class="col-md-3">終了日</label>
            <div class="col-md-9">
              <%= @reservation.end_date.strftime("%Y年 %m月 %d日") %>
            </div>
          </div>
        </div>

        <div class="update-content">
          <div class="row">
            <label for="total_price" class="col-md-3">価格</label>
            <div class="col-md-9">
              <%= @reservation.total_price %>円
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="container-fuild room-new">
  <div class="row">
    
    <div class="col-lg-2 room-nav room-nav-pc d-lg-block d-none">
      <ul>
        <li class="active">
          <%= link_to "基本情報", new_room_path %>
        </li>
      </ul>
    </div>

    <div class="col-lg-2 room-nav room-nav-mobile d-lg-none">
      <ul>
        <li class="active">
          <%= link_to "基本情報", new_room_path %>
        </li>
      </ul>
    </div>

    <div class="col-lg-10 room-view">
      <div class="room-view-box">
        <div class="update-content">
          <div class="row">
            <h5>ルーム情報登録</h5>
          </div>
        </div>

        <%= form_with url: rooms_path, :multipart => true do |f| %>
          <div class="update-content">
            <div class="row">
                <%= f.label :name,"ルーム名", class:"col-md-3 required-a" %>
                <%= f.text_field :name, value: @room.name, required: true, placeholder:"ルーム名を入力", class:"form-control col-md-9 mb-4" %>
            </div>
          </div>

          <div class="update-content">
            <div class="row">
                <%= f.label :introduction,"ルーム紹介",class:"col-md-3 required-a" %>
                <%= f.text_area :introduction, value: @room.introduction, rows:"5", required: true, placeholder:"ルーム説明を入力", class:"form-control mb-4 col-md-9" %>
            </div>
          </div>
          
          <div class="update-content">
            <div class="row">
              <%= f.label :price,"料金",class:"col-md-3 required-a" %>
              <%= f.number_field :price, value: @room.price, rows:"5", required: true, min: 1, placeholder:"1日あたりの料金を入力", class:"form-control mb-4 col-md-9" %>
            </div>
          </div>

          <div class="update-content">
            <div class="row">
                <%= f.label :address,"住所",class:"col-md-3 required-a" %>
                <%= f.text_field :address, value: @room.address, rows:"5", required: true, placeholder:"住所を入力", class:"form-control mb-4 col-md-9" %>
            </div>
          </div>

          <div class="update-content">
            <div class="row">
              <%= f.label :image, "ルーム画像", class:"col-md-3 required-a" %>
              <%= f.file_field :image, required: true, class:"mb-4 col-md-9" %>
            </div>
          </div>

          <%= f.hidden_field :user_id, value: @user.id %>
          
          <div class="update-content">
            <div class="row">
              <%= f.submit "登録", class: "col-md-2 btn btn-primary mx-3" %>
            </div>
          </div>
        <% end %>
        
      </div>
    </div>

  </div>
</div>

app/views/rooms/posts.html.erb
<div class="conainer-fiuld room-posts">
  <h4 class="pb-4">登録済みルーム一覧</h4>
  <table>
    <thead>
      <tr align="center">
        <th>ルーム画像</th>
        <th>ルーム名</th>
        <th>ルーム紹介</th>
        <th>料金</th>
        <th>作成日</th>
      </tr>
    </thead>

    <% @rooms.each do |room| %>
      <tbody>
        <tr>
          <td>
            <%= link_to image_tag(room.image.url, alt: "ルーム画像", class: "room-posts-image"), room_path(room.id) %>
          </td>
          <td class="posts-name">
            <%= link_to room.name, room_path(room.id) %>
          </td>
          <td class="posts-content">
            <%= room.introduction %>
          </td>
          <td class="price-icon">
            <%= room.price %>
          </td>
          <td>
            <%= room.created_at %>
          </td>
        </tr>
      </tbody>
      <% end %>

  </table>
</div>

app/views/rooms/search.html.erb
<div class="container-fiuld room">

  <% if @results.count != 0 %>
    <h4 class="pb-4">検索結果：<%= @results.count %>件</h4>
  <% else %>
    <h4 class="pb-4">検索結果：0件</h4>
  <% end %>
  
  <div class="row">
    
      <% @results.each do |result| %>
        <div class="col-sm-6 col-lg-4 col-xl-3">
          <div class="room-frame-inner">

            <%= link_to room_path(result.id) do %>
              <div class="room-image-out">
                <%= image_tag(result.image.url, alt: "ルーム画像", class: "room-image")  %>
              </div>
              <div class="room-profile">
                <p class="room-profile-name"><%= result.name %></p>
                <p class="room-profile-city"><%= result.address %></p>
                <p class="room-profile-price price-icon"><%= result.price %></p>
              </div>
            <% end %>

          </div>
        </div>
      <% end %>

  </div>

</div>

app/views/rooms/show.html.erb
<div class="container room-show">
  <div class="row">

    <div class="col-md-8">
      <%= image_tag @room.image.url, alt: "ルーム画像", class: "room-show-image" %>
      <div class="room-show-detile">
        <div class="room-show-detile-icon">

          <% if @user.image.blank? %>
            <%= link_to image_tag("https://presite-potepancamp-rails-02.herokuapp.com/assets/default_icon-9263fc59c414b7228d256fc178dcb22183561357950a68f5ad086ba7ee054974.jpg", alt: "ユーザー画像", class: "icon-image host-icon"), root_path %>
          <% else %>
            <%= link_to image_tag(@user.image.url, alt: "ユーザー画像", class: "icon-image host-icon"), root_path %>
          <% end %>  
          
        </div>
        <div class="room-show-profile">
          <p class="room-show-profile-name">
            <%= @room.name %>
          </p>
          <p class="room-show-profile-address">
            <%= @room.address %>
          </p>
        </div>
      </div>
      <p class="room-show-detile-content">
        <%= @room.introduction %>
      </p>
    </div>

    <div class="col-md-4">
      <div class="room-show-nav">
        <h5 class="price-icon">
          <%= "#{@room.price} / 日" %>
        </h5>
        <div class="room-show-date-select">

          <%= form_with model: @reservations, method: :get, url: new_reservation_path, :multipart => true do |f| %>

            <%= f.label :start_date, "開始日" %>
            <%= f.date_field :start_date, required: true, id: "start_date", class: "form-control mb-4" %>

            <%= f.label :end_date, "終了日" %>
            <%= f.date_field :end_date, required: true, id: "end_date", class: "form-control mb-4" %>

            <%= f.label :num_person, "人数" %>
            <%= f.number_field :num_person, required: true, min: 1, id: "person_num", class: "form-control mb-4" %>

            <%= f.hidden_field :room_id, value: @room.id, id: "room_id" %>

            <%= f.submit "予約する", class: "btn btn-primary form-control" %>
            
          <% end %>

        </div>
      </div>
    </div>

  </div>
</div>

app/views/users/account.html.erb
<div class="container-fuild user">
  <div class="row">

    <div class="col-lg-2 user-nav user-nav-pc d-lg-block d-none">
      <ul>
        <li class="active">
          <%= link_to "アカウント", users_account_path %>
        </li>
        <li>
          <%= link_to "プロフィール", users_profile_path %>
        </li>
      </ul>
    </div>

    <div class="col-lg-2 user-nav user-nav-mobile d-lg-none">
      <ul>
        <li class="active">
          <%= link_to "アカウント", users_account_path %>
        </li>
        <li>
          <%= link_to "プロフィール", users_profile_path %>
        </li>
      </ul>
    </div>

    <div class="col-lg-10 user-view">
      <div class="user-view-box">
        <div class="update-content">
          <div class="row">
            <h5>アカウント</h5>
          </div>
        </div>
        <div class="update-content">
          <div class="row">
            <label class="col-md-3" for="email">メールアドレス</label>
            <div class="col-md-9"><%= current_user.email %></div>
          </div>
        </div>
        <div class="update-content">
          <div class="row">
            <label class="col-md-3" for="password">パスワード</label>
            <div class="col-md-9">**********</div>
          </div>
        </div>
        <div class="update-content">
          <div class="row">
            <%= link_to "編集", edit_user_registration_path, class: "col-md-2 btn btn-primary mx-3" %>
          </div>
        </div>
      </div>
    </div>
    
  </div>
</div>

app/views/users/profile.html.erb
<div class="container-fuild user">
  <div class="row">
    
    <div class="col-lg-2 user-nav user-nav-pc d-lg-block d-none">
      <ul>
        <li>
          <%= link_to "アカウント", users_account_path %>
        </li>
        <li class="active">
          <%= link_to "プロフィール", users_profile_path %>
        </li>
      </ul>
    </div>

    <div class="col-lg-2 user-nav user-nav-mobile d-lg-none">
      <ul>
        <li>
          <%= link_to "アカウント", users_account_path %>
        </li>
        <li class="active">
          <%= link_to "プロフィール", users_profile_path %>
        </li>
      </ul>
    </div>

    <div class="col-lg-10 user-view">
      <div class="user-view-box">
        <div class="update-content">
          <div class="row">
            <h5>プロフィール</h5>
          </div>
        </div>

        <%= form_with url: users_profile_path, :multipart => true do |f| %>

          <div class="update-content">
            <div class="row">
                <div class="col-md-6 offset-md-3" %>
                    <div class="icon-box">

                        <% if @user.image.blank? %>
                          <img src="https://presite-potepancamp-rails-02.herokuapp.com/assets/default_icon-9263fc59c414b7228d256fc178dcb22183561357950a68f5ad086ba7ee054974.jpg" alt='プロフィール画像' class="icon-image host-icon">
                        <% else %>
                          <%= image_tag @user.image.url, alt: "プロフィール画像", class: "icon-image host-icon" %>
                        <% end %>  

                    </div>
                </div>
            </div>
          </div>

          <div class="update-content">
            <div class="row">
              <%= f.label :image, "アイコン画像", class:"col-md-3 required-a" %>
              <%= f.file_field :image, required: true, class:"mb-4 col-md-9" %>
            </div>
          </div>

          <div class="update-content">
            <div class="row">
                <%= f.label :name,"名前", class:"col-md-3 required-a" %>
                <%= f.text_field :name, value: @user.name, required: true, placeholder:"名前を入力", class:"form-control col-md-9 mb-4" %>
            </div>
          </div>

          <div class="update-content">
            <div class="row">
                <%= f.label :profile,"自己紹介",class:"col-md-3 required-a" %>
                <%= f.text_area :profile, value: @user.profile, rows:"5", required: true, placeholder:"自己紹介を入力", class:"form-control mb-4 col-md-9" %>
            </div>
          </div>
          
          <div class="update-content">
            <div class="row">
              <%= f.submit "更新", class: "col-md-2 btn btn-primary mx-3" %>
            </div>
          </div>
        
        <% end %>
      </div>
    </div>

  </div>
</div>